import { GoogleGenAI } from "@google/genai";
import { AI_CONFIG } from "../config/ai.config.js";

// AI validation schema for drug analysis
export const ANALYSIS_SCHEMA = {
  type: "object",
  properties: {
    name:           { type: "string" },
    moa:            { type: "string" },
    target:         { type: "string" },
    indication:     { type: "string" },
    adme:           { type: "string" },
    verdict:        { type: "string", enum: ["BENEFICIAL", "RISKY", "TOXIC", "INERT", "CONTROLLED SUBSTANCE"] },
    verdict_reason: { type: "string" },
    warnings:       { type: "array", items: { type: "string" } },
    similar_drugs:  { type: "array", items: { type: "string" } },
    novelty:        { type: "string" },
  },
  required: ["name", "moa", "target", "indication", "adme", "verdict", "verdict_reason", "warnings", "similar_drugs", "novelty"],
};

/**
 * Generic modular function to call the AI provider with a configurable 2-stage fallback.
 * Can be reused anywhere in the app for varying LLM tasks.
 * 
 * @param {string} prompt - The question or task for the AI
 * @param {object} schema - (Optional) JSON schema object to enforce structured outputs
 * @returns {Promise<any>} The parsed JSON or text generated by the AI
 */
export async function callLLM(prompt, schema = null) {
  // 1. Attempt Primary Google Model
  try {
    return await callGoogleGenAI(prompt, AI_CONFIG.google.models.primary, schema);
  } catch (error) {
    console.warn(`[callLLM] Primary Google model (${AI_CONFIG.google.models.primary}) failed:`, error);
  }

  // 2. Attempt Fallback Google Model (2nd stage model in same provider)
  try {
    console.log(`[callLLM] Attempting Google fallback model: ${AI_CONFIG.google.models.fallback}...`);
    return await callGoogleGenAI(prompt, AI_CONFIG.google.models.fallback, schema);
  } catch (error) {
    console.warn(`[callLLM] Fallback Google model (${AI_CONFIG.google.models.fallback}) failed:`, error);
  }

  // 3. Fallback tracking Provider: OpenRouter
  try {
    console.log("[callLLM] Attempting OpenRouter Fallback Provider...");
    return await callOpenRouter(prompt, AI_CONFIG.openrouter.models.default, schema);
  } catch (error) {
    console.error("[callLLM] All AI Fallbacks exhausted. Final error:", error);
    throw new Error("All AI providers failed. " + error.message);
  }
}

/**
 * Specific method for the drug designer analysis. 
 * Abstracts details away from the UI screen.
 */
export async function analyzeDrugComponents(componentsArray) {
  const components = componentsArray.map((c) => c.sym).join(", ");
  const prompt = `You are a medicinal chemist and pharmacologist. A pharmacy student has assembled the following chemical components for a hypothetical drug molecule: [${components}]. Analyze this combination and return a pharmacological assessment.`;

  const rawJsonInfo = await callLLM(prompt, ANALYSIS_SCHEMA);
  
  // Custom validation specific to the drug designer needs
  if (!rawJsonInfo.verdict || !rawJsonInfo.name || !rawJsonInfo.moa) {
    throw new Error("Invalid schema structure returned by model.");
  }
  
  return rawJsonInfo;
}

async function callGoogleGenAI(prompt, modelId, schema) {
  if (!AI_CONFIG.google.apiKey) {
    throw new Error("No Google Gen AI API key provided in environment.");
  }
  
  const ai = new GoogleGenAI({ apiKey: AI_CONFIG.google.apiKey });
  
  const config = {};
  if (schema) {
    config.responseMimeType = "application/json";
    config.responseSchema = schema;
  }

  const response = await ai.models.generateContent({
    model: modelId,
    contents: prompt,
    config,
  });

  const text = response.text;
  if (!text) throw new Error("Empty response from Google Gen AI.");

  return schema ? JSON.parse(text) : text;
}

async function callOpenRouter(prompt, modelId, schema) {
  if (!AI_CONFIG.openrouter.apiKey) {
    throw new Error("No OpenRouter API key provided in environment.");
  }

  const requestBody = {
    model: modelId,
    messages: [{ role: "user", content: prompt }],
    max_tokens: 1000,
  };

  if (schema) {
    requestBody.response_format = {
      type: "json_schema",
      json_schema: {
        name: "structured_output",
        strict: true,
        schema: { ...schema, additionalProperties: false },
      },
    };
  }

  const res = await fetch(AI_CONFIG.openrouter.endpoint, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      Authorization: `Bearer ${AI_CONFIG.openrouter.apiKey}`,
    },
    body: JSON.stringify(requestBody),
  });

  const data = await res.json();
  const finishReason = data.choices?.[0]?.finish_reason;
  const text = data.choices?.[0]?.message?.content || "";

  if (!text || finishReason === "length" || data.error) {
    throw new Error(data.error?.message || "model_failure");
  }

  return schema ? JSON.parse(text) : text;
}
